### ISSUE TITLE
File not found exception (App crash)

### ISSUE THREAD

**Issue by Patch4Code** [Patch4Code/MovieAppUi#11]
The issue likely arises during data import because the profile and banner images are not exported along with the data. However, the paths to these images are still saved. Consequently, when updating the public profile, the application attempts to access these nonexistent files, leading to a crash.

`FATAL EXCEPTION: main
                                                                                                    Process: com.patch4code.loglinemovieapp, PID: 28890
                                                                                                    java.io.FileNotFoundException: /data/user/0/com.patch4code.loglinemovieapp/files/profile_image.jpg: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:160)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:115)
                                                                                                    	at android.content.ContentResolver.openInputStream(ContentResolver.java:1542)
                                                                                                    	at com.patch4code.loglinemovieapp.features.social.presentation.screen_social.SocialViewModel$updatePublicProfile$1.invokeSuspend(SocialViewModel.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8377)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@40aeaae, Dispatchers.Main.immediate]
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8256)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:560)`

**Comment by Patch4Code** [comment]
This issue should be resolved now as profile and banner images are also included in the export. However, the social feature where this error occurred is currently not part of the app for the time being.
